services:
  - type: web
    name: streettuned-logcheck-api
    runtime: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

  - type: web
    name: streettuned-mopar-logcheck-api
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_mopar.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
